FROM lasery/kodi:17.6

USER root

RUN apt-get install -qy \
      python-pip

RUN pip install ipdb==0.8 pytest behave

COPY --chown=kodi addons/script.hello.world/ /home/kodi/.kodi/addons/script.hello.world/

USER kodi

