---
REPO: codebench
IMAGE_VERSION: python
STAGE: false
BASE_IMAGE: python

ARCH:
- name: armv6l
  tag: armv6l
  arch: arm
  variant: v6l
  platform: linux/arm/v6
  is_arm: true
  enable: false
  # enable: true

- name: armv7l
  tag: armv7l
  arch: arm
  variant: v7l
  platform: linux/arm/v7
  is_arm: true
  enable: false
  # enable: true

- name: amd64
  tag: amd64
  arch: amd64
  platform: linux/amd64
  is_amd: true
  enable: true
