FROM {{BASE_IMAGE}}

RUN pip3 install ipdb pytest behave

RUN useradd -ms /bin/bash python
COPY --chown=python code/ /home/python/code/
COPY --chown=python README.md /

USER python
WORKDIR /home/python/code/

